import Head from "next/head";
import Header from "../../components/Header";
import Feed from "../../components/Feed";
import Users from "../../components/Users";
import Sidebar from "../../components/Sidebar";
import { Toaster } from "react-hot-toast";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Toaster />
        <Header />
        <Feed />
        <Users />
        <Sidebar />
      </main>
    </div>
  );
}
